### ISSUE TITLE
Bad linky on pypi page

### ISSUE THREAD

**Issue by slavkoja** [mrshu/stemm-sk#1]
Hi,

nice to see slovak stemmer, but on Python package index is bad link to homepage:

https://github.com/mrshu/mrshu/stemm-sk

krásny zvyšok dňa ;)

**Comment by mrshu** [comment]
@slavkoja Thanks a ton.

I fixed this is f3d2e181fd1d2eb473ca840184b65e918d8eea86 and a new version should already by live on PyPI (https://pypi.python.org/pypi/stemmsk).

The stemmer is in a very early stage, I am very open to contributions of any kind =)

Thanks again!
